- name: Install grafana
  hosts: entrypoint
  roles:
  - aws

  tasks:
  - name: Create app folder
    file:
      path: /apps/grafana
      state: directory
      mode: '0755'
  - name: Create data folder
    file:
      path: /apps/grafana/data
      state: directory
      mode: '0755'
  - name: Inject Configuration file
    copy:
      src: grafana.ini
      dest: /apps/grafana/grafana.ini
  - name: Run grafana in docker
    docker_container:
      name: grafana
      image: grafana/grafana
      state: started
      user: "1001:1001" # ansible gid
      restart: true
      restart_policy: unless-stopped
      pull: true
      networks:
      - name: homelab
      volumes:
      - /apps/grafana/grafana.ini:/etc/grafana/grafana.ini
      - /apps/grafana/data:/var/lib/grafana
      detach: true
  - name: "Add cron for backup"
    ansible.builtin.cron:
      name: "Backup grafana data"
      minute: "30"
      hour: "22"
      job: "/scripts/backup_aws.sh /apps/grafana/data s3://{{ aws_backup_bucket }}/grafana/data"

