- name: Run Poseidon
  hosts: home

  tasks:
  - name: Run poseidon
    docker_container:
      name: poseidon
      image: yomain/poseidon
      state: started
      pull: true
      platform: linux/arm/v7
      restart_policy: unless-stopped
      networks:
      - name: homelab
      detach: true
