- name: Run Aristaeus service
  hosts: home
  roles:
  - akingbee

  tasks:
  - name: Run Aristaeus Api
    docker_container:
      name: aristaeus-api
      image: yomain/aristaeus
      state: started
      pull: true
      restart_policy: unless-stopped
      capabilities:
      - SYS_PTRACE
      command:
      - uvicorn
      - --host
      - 0.0.0.0
      - --port
      - 80
      - --proxy-headers
      - --workers
      - 4
      - aristaeus.controllers.api.app:create_app
      # command:
      # - gunicorn
      # - aristaeus.controllers.api.app:create_app
      # - --bind
      # - 0.0.0.0:80
      # - --workers
      # - 4
      # - --worker-class
      # - uvicorn.workers.UvicornWorker
      networks:
      - name: homelab
      detach: true
      env:
        SERVICE_NAME: "aristaeus-api"
        EXECUTE_MIGRATION: "true"
        AKB_DISABLE_CORS: "true"
        AKB_ENV: development
        AKB_DATABASE_HOST: "{{ database_host }}"
        AKB_DATABASE_USER: "{{ aristaeus_db_user }}"
        AKB_DATABASE_PASSWORD: "{{ aristaeus_db_password }}"
        AKB_DATABASE_DBNAME: "{{ aristaeus_db_name }}"
        AKB_JWT_KEY: "{{ cerbes_jwt_key }}"
        AKB_CERBES_API_ENDPOINT: "http://cerbes"
        AKB_CERBES_API_PORT: "80"
  - name: Run Aristaeus Listener
    docker_container:
      name: aristaeus-listener
      image: yomain/aristaeus
      state: started
      pull: true
      restart_policy: unless-stopped
      networks:
      - name: homelab
      detach: true
      command:
      - python
      - aristaeus/controllers/consumers/app.py
      env:
        SERVICE_NAME: aristaeus-api
        AKB_ENV: development
        AKB_DATABASE_HOST: "{{ database_host }}"
        AKB_DATABASE_USER: "{{ aristaeus_db_user }}"
        AKB_DATABASE_PASSWORD: "{{ aristaeus_db_password }}"
        AKB_DATABASE_DBNAME: "{{ aristaeus_db_name }}"
        AKB_ZEROMQ_HOST: "cerbes"
        AKB_ZEROMQ_PORT: "5555"
