[tool.poetry]
name = "homelab"
version = "0.1.0"
description = ""
authors = ["rarnal <arnal.romain@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
ansible = "^7.1.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
