[tool.poetry]
name = "homelab"
version = "0.1.0"
description = ""
authors = ["rarnal <arnal.romain@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.11"
ansible = "^7.1.0"
boto3 = "^1.26.151"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
