- name: Run firefly service
  hosts: home
  roles:
  - aws
  - firefly
  - sudo

  tasks:
  - name: Create app folder
    become: true
    file:
      path: /apps/firefly/storage
      state: directory
      mode: '0775'
      owner: 'ansible'
      group: 'www-data'
  - name: Create app folder
    become: true
    file:
      path: /apps/firefly/storage/database
      state: directory
      mode: '0775'
      owner: 'ansible'
      group: 'www-data'
  - name: Run firefly
    docker_container:
      name: firefly
      image: fireflyiii/core
      state: started
      pull: true
      restart_policy: unless-stopped
      networks:
      - name: homelab
      detach: true
      volumes:
      - /apps/firefly/storage:/var/www/html/storage
      env:
        # see https://raw.githubusercontent.com/firefly-iii/firefly-iii/main/.env.example
        APP_ENV: "production"
        APP_DEBUG: "false"
        SITE_OWNER: "{{ email }}"
        APP_KEY: "{{ app_key }}"
        APP_URL: "{{ app_url }}"
        DEFAULT_LANGUAGE: "en_US"
        TZ: "Europe/Paris"
        TRUSTED_PROXIES: "*"
        APP_LOG_LEVEL: "notice"
        DB_CONNECTION: "sqlite"

  - name: "Add cron for backup"
    ansible.builtin.cron:
      name: "Backup firefly data"
      minute: "30"
      hour: "22"
      job: "/scripts/backup_aws.sh /apps/firefly/storage s3://{{ aws_backup_bucket }}/firefly/storage"

