- name: Setup postgres database
  hosts: 
    - raspberries

  roles:
  - postgres
  - aws

  tasks:
  - name: Create app folder
    file:
      path: /apps/postgres
      state: directory
      mode: '0755'
      owner: "ansible"
  - name: Copy user script
    copy:
      src: users.sh
      dest: /apps/postgres/users.sh
  - name: Run postgres in docker
    docker_container:
      name: postgres
      image: postgres:15
      state: started
      pull: true
      # https://stackoverflow.com/questions/56188573/permission-issue-with-postgresql-in-docker-container
      # only set the user id once the folder will have been created
      user: "1001:1001" # ansible gid
      exposed_ports:
      - 5432
      restart_policy: unless-stopped
      networks:
      - name: homelab
      platform: linux/arm/v7
      detach: true
      volumes:
      - /apps/postgres/data:/var/lib/postgresql/data
      - /apps/postgres/users.sh:/scripts/users.sh
      env:
        POSTGRES_PASSWORD: "{{ postgres_password }}"
        POSTGRES_USER: "{{ postgres_user }}"
        POSTGRES_DB: postgres
  - name: "Add cron for backup"
    ansible.builtin.cron:
      name: "Backup postgres data"
      minute: "15"
      hour: "22"
      job: "/scripts/backup_aws.sh /apps/postgres/data s3://{{ aws_backup_bucket }}/postgres/data"

