- name: Run Hermes service
  hosts: home
  roles:
  - akingbee

  tasks:
  - name: Run Hermes Api
    docker_container:
      name: hermes
      image: yomain/hermes
      state: started
      pull: true
      platform: linux/arm/v7
      restart_policy: unless-stopped
      networks:
      - name: homelab
      detach: true
      env:
        SERVICE_NAME: "hermes"
        AKB_EMAIL_SERVER_HOST: "{{ email_server_host }}"
        AKB_EMAIL_SERVER_PORT: "{{ email_server_port }}"
        AKB_NOREPLY_EMAIL: "{{ email_no_reply }}"
        AKB_NOREPLY_EMAIL_PASSWORD: "{{ email_no_reply_password }}"
        AKB_ZEROMQ_HOST: "cerbes"
        AKB_ZEROMQ_PORT: "5555"
