- name: Run Hermes service
  hosts: home
  roles:
  - akingbee

  tasks:
  - name: Run Hermes Api
    docker_container:
      name: hermes
      image: yomain/hermes
      state: started
      pull: true
      platform: linux/arm/v7
      restart_policy: unless-stopped
      networks:
      - name: homelab
      detach: true
      env:
        SERVICE_NAME: "hermes"
        AKB_RBMQ_HOST: rbmq
        AKB_RBMQ_USER: "{{ rbmq_user }}"
        AKB_RBMQ_PASSWORD: "{{ rbmq_pass }}"
        AKB_RBMQ_PORT: "5672"
        AKB_RBMQ_VHOST: "/"
        AKB_EMAIL_SERVER_HOST: "{{ email_server_host }}"
        AKB_EMAIL_SERVER_PORT: "{{ email_server_port }}"
        AKB_EMAIL_NO_REPLY: "{{ email_no_reply }}"
        AKB_EMAIL_NO_REPLY_PASSWORD: "{{ email_no_reply_password }}"
