- name: Run pihole
  hosts: entrypoint
  roles:
  - pihole

  tasks:
  - name: Create app folder
    file:
      path: /apps/pihole
      state: directory
      mode: '0755'
  - name: Run image in docker
    docker_container:
      name: pihole
      image: pihole/pihole:2025.06.2
      state: started
      env:
        TZ: "Europe/Paris"
        FTLCONF_webserver_api_password: '{{ pihole_password }}'
      pull: true
      restart_policy: unless-stopped
      volumes:
      - "apps/pihole/data/etc/pihole:/etc/pihole"
      # See https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
      cap_add:
      # Required if you are using Pi-hole as your DHCP server, else not needed
      - NET_ADMIN
      # Required if you are using Pi-hole as your NTP client to be able to set the host's system time
      - SYS_TIME
      networks:
      - name: homelab
      detach: true
