- name: "Add script to backup folder in aws s3"
  hosts:
  - raspberries
  roles:
  - aws
  - sudo

  tasks:
  - name: "Create script folder"
    become: true
    file:
      path: /scripts
      state: directory
      mode: '0777'
  - name: "Copy backup script"
    ansible.builtin.copy:
      src: ../../../scripts/backup_aws.sh
      dest: /scripts/backup_aws.sh
      mode: '0777'
  - name: "Create aws folder"
    ansible.builtin.file:
      path: "~/.aws"
      state: directory
  - name: "Create credentials file"
    ansible.builtin.file:
      path: "~/.aws/credentials"
      state: touch
  - name: "Add content in aws credentials file"
    ansible.builtin.copy:
      dest: "~/.aws/credentials"
      content: |
        [default]
        aws_access_key_id={{ aws_access_key }}
        aws_secret_access_key={{ aws_secret_key }}
  - name: "Add ansible user in node-exp group"
    become: true
    ansible.builtin.user:
        append: true
        name: ansible
        groups: 
          - node-exp
