- name: Install docker
  hosts:
  - raspberries
  become: true
  roles:
  - sudo

  tasks:
  - name: Install dependencies
    apt: 
      update_cache: true
      pkg:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
  - name: add docker gpg key
    apt_key: 
      url: https://download.docker.com/linux/debian/gpg
      state: present
  - name: Add docker repository
    apt_repository: 
      repo: deb https://download.docker.com/linux/debian bullseye stable
      filename: docker
  - name: Install docker engine and docker compose
    apt: 
      update_cache: true
      pkg:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-compose-plugin
  - name: Create docker group
    group: 
      name: docker
  - name: Add ansible user to docker group
    user: 
      name: ansible
      groups: docker
      append: true
  - name: Create docker homelab network
    docker_network:
      name: homelab
  - name: Create daemon.json file
    copy:
      dest: /etc/docker/daemon.json
      content: |
        {
          "metrics-addr" : "127.0.0.1:9323"
        }
