- name: Run Rabbitmq service
  hosts: home
  roles:
  - akingbee

  tasks:
  - name: Run rabbitmq in docker
    docker_container:
      name: rbmq
      image: rabbitmq:management-alpine
      state: started
      pull: true
      restart_policy: unless-stopped
      networks:
      - name: homelab
      detach: true
      env:
        RABBITMQ_DEFAULT_USER: "{{ rbmq_user }}"
        RABBITMQ_DEFAULT_PASS: "{{ rbmq_pass }}"
